config/routes.rb
QueryStringVerbs::Application.routes.draw do
  
  root to: "pages#home"
  # Locations - modifying scaffolding
  resources :locations, only: [:index, :show]
  
  get      'locations?v=new',       to: 'locations#index',  as: 'new_location'
  post     'locations(?v=create)',  to: 'locations#index'

  scope 'locations' do 
    get     ':id?v=edit',           to: 'locations#show',   as: 'edit_location'
    put     ':id(?v=update)',       to: 'locations#show'
    patch   ':id(?v=update)',       to: 'locations#show'
    delete  ':id(?v=destroy)',      to: 'locations#show'
  end

  # Users - built from scratch, using same verbs as scaffolding, but different actions
  get     'users',                  to: 'users#list',        as: 'users'
  get     'users?v=new',            to: 'users#list',        as: 'new_user'
  post    'users(?v=create)',         to: 'users#list'
  
  scope 'users' do  
    get     ':id',                  to: 'users#view',        as: 'user'
    get     ':id?v=edit',           to: 'users#view',        as: 'edit_user'
    put     ':id(?v=update)',       to: 'users#view'
    patch   ':id(?v=update)',       to: 'users#view'
    delete  ':id(?v=destroy)',      to: 'users#view'
  end

end

app/models/location.rb
class Location < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController

  def index
    @locations = Location.all

    if params[:v] == "new" # GET
  
      @location = Location.new
      @path = 'locations/?v=create'

    elsif params[:v] == "create" # POST

      @location = Location.new(location_params)

      respond_to do |format|
        if @location.save
          format.html { redirect_to @location, notice: 'Location was successfully created.' }
          format.json { render action: 'show', status: :created, location: @location }
        else
          format.html { render action: 'new' }
          format.json { render json: @location.errors, status: :unprocessable_entity }
        end
      end

    #else # GET
      # Additional code for the scaffolded index action would go here
    end
  end


  def show
    @location = Location.find(params[:id])

    if params[:v] == "edit" # GET

      @path = '/locations/'+params[:id]+'?v=update'

    elsif params[:v] == "update" and (params[:_method] == "patch" or params[:_method] == "put") # PATCH/PUT

      respond_to do |format|
        if @location.update(location_params)
          format.html { redirect_to @location, notice: 'Location was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: 'edit' }
          format.json { render json: @location.errors, status: :unprocessable_entity }
        end
      end

    elsif params[:v] == "destroy" and params[:_method] == "delete" # DELETE

      @location.destroy
      respond_to do |format|
        format.html { redirect_to locations_url }
        format.json { head :no_content }
      end

    #else # GET
      # Additional code for the scaffolded show action would go here

    end
  end


  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def location_params
      params.require(:location).permit(:name)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def list
  	@users = User.all

  	if params[:v] == "new" # GET
      @user = User.new
      @path = 'users/?v=create'

    elsif params[:v] == "create" # POST
    	@user = User.new(user_params)
	    if @user.save
	      redirect_to @user, notice: 'User was successfully created.'
	    else
	      render action: 'new'
	    end

    #else # GET
      # Additional code for list GET
    
    end

  end

  def view
  	@user = User.find(params[:id])

    if params[:v] == "edit" # GET

      @path = '/users/'+params[:id]+'?v=update'

    elsif params[:v] == "update" and (params[:_method] == "patch" or params[:_method] == "put") # PATCH/PUT

      if @user.update(user_params)
        redirect_to @user, notice: 'User was successfully updated.'
      else
        render action: 'edit'
      end

    elsif params[:v] == "destroy" and params[:_method] == "delete" # DELETE

      @user.destroy
      redirect_to users_url

    #else # GET
      # Additional code for view GET

    end
  end


  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email)
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>QueryStringVerbs</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/locations/_edit.html.erb
<h1>Editing location</h1>

<%= render 'form' %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/_form.html.erb
<%= form_for @location, :url => @path  do |f| %>
  <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% @location.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/locations/_location.html.erb
<p>
  <strong>Name:</strong>
  <%= @location.name %>
</p>

<%= link_to 'Edit', edit_location_path(@location) %> |
<%= link_to 'Back', locations_path %>

app/views/locations/_new.html.erb
<h1>New location</h1>

<%= render 'form' %>

<%= link_to 'Back', locations_path %>

app/views/locations/_table.erb
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @locations.each do |location| %>
      <tr>
        <td><%= location.name %></td>
        <td><%= link_to 'Show', location %></td>
        <td><%= link_to 'Edit', edit_location_path(location) %></td>
        <td><%= link_to 'Destroy', location_path(location) + '?v=destroy', method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/locations/edit.html.erb
<h1>Editing location</h1>

<%= render 'form' %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/index.html.erb
<h1>Listing locations</h1>

<% if params[:v] == 'new' %>
  <%= render 'new' %>
<% else %>
  <%= render 'table' %>
  <%= link_to 'New Location', new_location_path %>
<% end %>

<br>

app/views/locations/new.html.erb
<h1>New location</h1>

<%= render 'form' %>

<%= link_to 'Back', locations_path %>

app/views/locations/show.html.erb
<p id="notice"><%= notice %></p>

<% if params[:v] == 'edit' %>
  <%= render 'edit' %>
<% else %>
  <%= render 'location' %>
<% end %>

app/views/pages/home.html.erb
<h1>Query String Verbs</h1>
Two Examples Below:
<ul>
	<li>Scaffolding modified: <%= link_to 'Locations Example', locations_path %> </li>
	<li>Slightly more custom: <%= link_to 'Users Example', users_path %> </li>
</ul>

<p>Check out <a href="https://github.com/railsdemo/query-string-verbs">github repo</a>.  The readme has more information.</p>

app/views/users/_edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/_form.html.erb
<%= simple_form_for @user, :url => @path  do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.input :name %>
  <%= f.input :email %>
  <%= f.submit %>
<% end %>

app/views/users/_new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/_table.erb
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user_path(user) + '?v=destroy', method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_user.html.erb
<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/users/list.html.erb
<h1>Listing users</h1>

<% if params[:v] == 'new' %>
  <%= render 'new' %>
<% else %>
  <%= render 'table' %>
  <%= link_to 'New User', new_user_path %>
<% end %>

<br>

app/views/users/view.html.erb
<p id="notice"><%= notice %></p>

<% if params[:v] == 'edit' %>
  <%= render 'edit' %>
<% else %>
  <%= render 'user' %>
<% end %>